print(type(19.0))
print(type(None))
print(type([16, 19, 13]))
print(type(True))
print(type(False))
print(type(['[]']))
print(type('13.0'))
print(type(16))
print(type((False, True)))
print(type('True'))