print(type('23.0'))
print(type(14.0))
print(type([16, 14, 23]))
print(type(True))
print(type(False))
print(type(['[]']))
print(type(None))
print(type(16))
print(type((False, True)))
print(type('True'))